# Generated by Django 2.2.2 on 2019-06-11 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestflightUser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='international_passport_number',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True),
        ),
    ]
