language: python

python:
  - "3.6"

sudo:
  - required

cache:
  pip: true

branches:
  only:
    - master
    - develop

services:
  - postgresql

install: pip install pipenv

script:
  - pipenv shell
  - make travis_test