version: "3.3"

services:
  bestflight-db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=best_flight
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

  bestflight:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - bestflight-db
    environment:
    - DATABASE_URL=postgres://postgres:password@bestflight-db:5432/best_flight

