# Generated by Django 2.2.2 on 2019-06-15 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=225, unique=True)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='AirlineFlightPath',
            fields=[
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pick_up', models.CharField(max_length=225)),
                ('destinaton', models.CharField(max_length=225)),
                ('should_reoccur', models.BooleanField(default=False)),
                ('reoccurrence_step', models.IntegerField(blank=True, null=True)),
                ('date_last_flight', models.DateTimeField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=225, unique=True)),
                ('total_capacity', models.IntegerField()),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='AvailableFlight',
            fields=[
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('boarding_time', models.DateTimeField()),
                ('take_off_time', models.DateTimeField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('no_reversaton', models.IntegerField(default=0)),
                ('airlinePath', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bestflightApp.AirlineFlightPath')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FlightClass',
            fields=[
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=225, unique=True)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feedback', models.TextField(blank=True, max_length=500, null=True)),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bestflightApp.AvailableFlight')),
                ('flight_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bestflightApp.FlightClass')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AirplaneCapacity',
            fields=[
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('capacity', models.IntegerField()),
                ('airplane', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bestflightApp.Airplane')),
                ('flight_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bestflightApp.FlightClass')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='airplane',
            name='capacities',
            field=models.ManyToManyField(through='bestflightApp.AirplaneCapacity', to='bestflightApp.FlightClass'),
        ),
        migrations.AddField(
            model_name='airlineflightpath',
            name='airplane',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bestflightApp.Airplane'),
        ),
    ]
