# Generated by Django 2.2.2 on 2019-06-15 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bestflightApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airlineflightpath',
            name='airline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bestflightApp.Airline'),
            preserve_default=False,
        ),
    ]
