# Generated by Django 2.2.2 on 2019-06-16 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bestflightApp', '0003_auto_20190615_1857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airlineflightpath',
            old_name='destinaton',
            new_name='destination',
        ),
    ]
