# Generated by Django 2.2.2 on 2019-06-17 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestflightApp', '0004_auto_20190616_1934'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='sent_reminder',
            field=models.BooleanField(default=False),
        ),
    ]
